

// for data.nba.com

type NBA struct {
	SportsContent struct {
		SportsMeta struct {
			DateTime   string `json:"date_time"`
			SeasonMeta struct {
				CalendarDate        int    `json:"calendar_date"`
				SeasonYear          int    `json:"season_year"`
				StatsSeasonYear     int    `json:"stats_season_year"`
				StatsSeasonID       int    `json:"stats_season_id"`
				StatsSeasonStage    int    `json:"stats_season_stage"`
				RosterSeasonYear    int    `json:"roster_season_year"`
				ScheduleSeasonYear  int    `json:"schedule_season_year"`
				StandingsSeasonYear int    `json:"standings_season_year"`
				SeasonID            int    `json:"season_id"`
				DisplayYear         string `json:"display_year"`
				DisplaySeason       string `json:"display_season"`
				SeasonStage         int    `json:"season_stage"`
			} `json:"season_meta"`
			Next struct {
				URL string `json:"url"`
			} `json:"next"`
		} `json:"sports_meta"`
		Teams struct {
			SeasonYear int `json:"season_year"`
			Team       []struct {
				IsNbaTeam     bool   `json:"is_nba_team"`
				TeamName      string `json:"team_name"`
				TeamNickname  string `json:"team_nickname"`
				TeamCode      string `json:"team_code"`
				TeamAbbrev    string `json:"team_abbrev"`
				City          string `json:"city"`
				State         string `json:"state"`
				TeamShortName string `json:"team_short_name"`
				TeamID        int    `json:"team_id"`
				Conference    string `json:"conference"`
				DivisionID    string `json:"division_id"`
			} `json:"team"`
		} `json:"teams"`
	} `json:"sports_content"`
}

type AutoGenerated struct {
	Gs struct {
		Mid  int64  `json:"mid"`
		Gdte string `json:"gdte"`
		Next string `json:"next"`
		G    []struct {
			Gid   string `json:"gid"`
			Gcode string `json:"gcode"`
			P     int    `json:"p"`
			St    int    `json:"st"`
			Stt   string `json:"stt"`
			Cl    string `json:"cl"`
			Seq   int    `json:"seq"`
			Lm    struct {
				Gdte string `json:"gdte"`
				Gres string `json:"gres"`
				Seri string `json:"seri"`
				Gid  string `json:"gid"`
			} `json:"lm"`
			V struct {
				Ta   string `json:"ta"`
				Q1   int    `json:"q1"`
				S    int    `json:"s"`
				Q2   int    `json:"q2"`
				Q3   int    `json:"q3"`
				Q4   int    `json:"q4"`
				Ot1  int    `json:"ot1"`
				Ot2  int    `json:"ot2"`
				Ot3  int    `json:"ot3"`
				Ot4  int    `json:"ot4"`
				Ot5  int    `json:"ot5"`
				Ot6  int    `json:"ot6"`
				Ot7  int    `json:"ot7"`
				Ot8  int    `json:"ot8"`
				Ot9  int    `json:"ot9"`
				Ot10 int    `json:"ot10"`
				Tn   string `json:"tn"`
				Tc   string `json:"tc"`
				Tid  int    `json:"tid"`
			} `json:"v"`
			H struct {
				Ta   string `json:"ta"`
				Q1   int    `json:"q1"`
				S    int    `json:"s"`
				Q2   int    `json:"q2"`
				Q3   int    `json:"q3"`
				Q4   int    `json:"q4"`
				Ot1  int    `json:"ot1"`
				Ot2  int    `json:"ot2"`
				Ot3  int    `json:"ot3"`
				Ot4  int    `json:"ot4"`
				Ot5  int    `json:"ot5"`
				Ot6  int    `json:"ot6"`
				Ot7  int    `json:"ot7"`
				Ot8  int    `json:"ot8"`
				Ot9  int    `json:"ot9"`
				Ot10 int    `json:"ot10"`
				Tn   string `json:"tn"`
				Tc   string `json:"tc"`
				Tid  int    `json:"tid"`
			} `json:"h"`
		} `json:"g"`
	} `json:"gs"`
}